
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import java.util.Random;

public class FirstTest {

  public CajaDeAhorro sut;
  public long randomLong;

  @Before
  public void beforeEach() {
    sut = new CajaDeAhorro(12983981, "Titular");
    randomLong = Math.abs(new Random().nextLong());
  }

  @Test
  public void testPuedoDepositarEnCajaDeAhorro() {

    long saldoAnterior = sut.getSaldo();
    long expected = saldoAnterior + randomLong;

    sut.depositar(randomLong);
    long current = sut.getSaldo();

    assertEquals("Deberian ser iguales", expected, current);
  }

  @Test
  public void testPuedoExtraerEnCajaDeAhorro() {

    long anotherRandom = Math.abs(new Random().nextLong());
    long montoMenor = Math.min(randomLong, anotherRandom);
    long montoMayor = Math.max(randomLong, anotherRandom);
    long saldoAnterior = sut.getSaldo();

    sut.depositar(montoMayor);
    long expected = saldoAnterior + montoMayor - montoMenor;
    sut.extraer(montoMenor);
    long current = sut.getSaldo();

    assertEquals("Deberian ser iguales", expected, current);
  }

  @Test
  public void testNoPuedoDepositarNegativoEnCajaDeAhorro() {
    long negativeLong = 0 - randomLong;
    assertTrue("Deberia ser positivo", negativeLong < 0);

    try {
      sut.depositar(negativeLong);
      fail("No deberia haber llegado hasta aca");
    } catch (Exception e) {
      System.out.println(e.getMessage());
      assertEquals(e.getMessage(), "No se puede depositar negativo");
    }
  }

  @Test
  public void testNoPuedoExtraerCuandoElSaldoEsInsuficienteEnCajaDeAhorro() {

    long anotherRandom = Math.abs(new Random().nextLong());
    long montoMenor = Math.min(randomLong, anotherRandom);
    long montoMayor = Math.max(randomLong, anotherRandom);
    sut.depositar(montoMenor);

    try {
      sut.extraer(montoMayor);
      fail("No deberia haber llegado hasta aca");
    } catch (Exception e) {
      System.out.println(e.getMessage());
      assertEquals(e.getMessage(), "No hay dinero suficiente");
    }
  }
}
